spring:
  mail:
    host: smtp.163.com
    username: 19568888784@163.com
    password: GZivY3ADHqDwepeN
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baima1
  data:
    redis:
      database: 6
  security:
    jwt:
      key: abcdefghijklmn
      expire: 24
